language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE="tls"
    - EXTRA_REMOTES="https://github.com/mirage/mirageos-3-beta.git"
  matrix:
    - OCAML_VERSION=4.02 DEPOPTS=lwt
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.03
      DEPOPTS="mirage-flow-lwt mirage-kv-lwt mirage-clock"
      POST_INSTALL_HOOK="./.travis-test-mirage.sh" TESTS=false
    - OCAML_VERSION=4.04
    - OCAML_VERSION=4.04 DEPOPTS=lwt
    - OCAML_VERSION=4.04
      DEPOPTS="mirage-flow-lwt mirage-kv-lwt mirage-clock"
      POST_INSTALL_HOOK="./.travis-test-mirage.sh" TESTS=false
notifications:
  email: false
